version: '3'
services:
  query_service:
    container_name: query-service
    build: .
    ports:
      - "8002:8002"
    env_file:
      - .env
  # Add Celery worker
  celery_worker:
    container_name: celery-worker
    build:
      context: ./worker
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
  redis:
    container_name: redis
    image: "redis:alpine"
  
  postgres:
    container_name: postgres-db
    image: "postgres:13"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"

  flower:
    container_name: celery-flower
    image: "mher/flower"
    command: celery flower --persisten=True
    environment:
      - CELERY_BROKER_URL=redis://redis/0
      - FLOWER_PORT=8888
    ports:
    - 8888:8888 # docker will expose this ports
#######################################
######## WEAVIATE SECTION #############
#######################################
  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: semitechnologies/weaviate:1.23.7
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    env_file:
      - .env
  t2v-transformers:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: '0'
  qna-transformers:
    image: semitechnologies/qna-transformers:distilbert-base-uncased-distilled-squad
    environment:
      ENABLE_CUDA: '0'
  sum-transformers:
    image: semitechnologies/sum-transformers:facebook-bart-large-cnn-1.0.0
    environment:
      ENABLE_CUDA: '0'
  reranker-transformers:
    image: semitechnologies/reranker-transformers:cross-encoder-ms-marco-MiniLM-L-6-v2
    environment:
      ENABLE_CUDA: '0'
volumes:
  weaviate_data:
    driver: local
